In [28]:
import pandas as pd
import json
import random

# Function to read JSON file in chunks
def read_json_in_chunks(file_path, chunk_size=1000):
    with open(file_path, 'r') as file:
        while True:
            chunk = []
            for _ in range(chunk_size):
                line = file.readline()
                if not line:
                    return
                try:
                    chunk.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
            yield chunk

# Function to take a random sample from each chunk
def take_random_sample_from_chunks(file_path, sample_size):
    sampled_data = []
    for chunk in read_json_in_chunks(file_path):
        sampled_data.extend(random.sample(chunk, min(sample_size, len(chunk))))
    return sampled_data

# Main function
def main():
    # Path to your JSON file
    json_file_path = 'Books_5.json'
    
    # Specify sample size
    sample_size = 100  # Change this to the desired sample size
    
    # Take a random sample from the JSON file
    sampled_data = take_random_sample_from_chunks(json_file_path, sample_size)
    
    # Optionally, write sampled data to a new JSON file
    with open('random_sample.json', 'w') as file:
        json.dump(sampled_data, file, indent=4)

if __name__ == "__main__":
    main()

In [29]:
df = pd.read_json('random_sample.json')

df.head()

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
0,5,True,"05 2, 2017",A353L9MM29O3UV,0002005263,{'Format:': ' Kindle Edition'},Steve Brannan,This has been one of the MOST captivating and ...,Intriguing!,1493683200,NaN,NaN
1,5,True,"05 23, 2013",A1PZ94AOBKDLZU,0001712799,{'Format:': ' Hardcover'},Amanda,A classic! I think children of all ages like t...,one of the best,1369267200,NaN,NaN
2,5,True,"08 10, 2013",AG5WO5CYX6C2R,0001932349,{'Format:': ' Hardcover'},susan clare knight,I love this little book which is wonderful to ...,I already have a copy of this book,1376092800,NaN,NaN
3,5,True,"01 3, 2015",A1M4W6GH7YX2WW,0001384198,{'Format:': ' Paperback'},ArmyWife111,"Small book about 5""x5"" and was a perfect stock...",A classic...,1420243200,NaN,NaN
4,5,False,"08 28, 2014",APUS1UN6XMBBA,0002005263,{'Format:': ' Mass Market Paperback'},Norma Cotton,excellent,Five Stars,1409184000,NaN,NaN